Eatler-Web-Application/Eatler/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from accounts.api import urls
from main import urls as mainurls
from main.api import urls as main_api_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),
    path('account_api/', include(urls)),
    path('index/',include(mainurls)),
    path('main_api/',include(main_api_urls)),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Eatler-Web-Application/main/api/urls.py
from django.urls import path
from main.api import views
from rest_framework.authtoken.views import obtain_auth_token





urlpatterns = [
    # path('hello/', views.HelloView.as_view(), name='hello'),
    path('query/',views.getQuery.as_view(), name="query"),
    path('product/',views.getProduct_without_param.as_view(), name="product_list"),
    path('product_android/',views.getProduct_without_param_android.as_view(), name="product_list_android"),
    path('product_get/',views.getProduct_with_param.as_view(), name="product_list_get"),
    path('address/',views.getCoordinates.as_view(), name="coordinates"),
    path('nearbyRestaurant/',views.getNearbyRestaurant_without_param.as_view(), name="nearbyRestaurant"),
    path('nearbyRestaurant_get/',views.getNearbyRestaurant_with_param.as_view(), name="nearbyRestaurant_get"),
    path('chatbot/',views.chatbot_integration_API.as_view(), name="chatbot"),
    path('orderdetails/',views.OrderDetails.as_view(), name="orderdetails"),
    path('userAddress/',views.getUserAddress.as_view(), name="userAddress"),
    path('deleteuserAddress/',views.deleteUserAddress.as_view(), name="deleteuserAddress"),
    path('adduserAddress/',views.AddUserAddress.as_view(), name="adduserAddress"),
    path('orderhistory/',views.OrdersHistory.as_view(), name="orderhistory"),
    path('orderstatus/',views.getOrderStatus.as_view(), name="orderstatus"),
    path('cancelorder/',views.cancelOrder.as_view(), name="cancelorder"),



    path('chatboturl/',views.Chatboturl.as_view(), name="chatboturl"),
    path('paymentStatus/',views.getPaymentStatus.as_view(), name="paymentStatus"),
    path('bookTable/',views.BookTableAPI.as_view(), name="bookTable"),
    path('getFeedback/',views.FeedbackAPI.as_view(), name="getFeedback"),

    path('restaurantFromCity/',views.getRestaurantFromCity.as_view(), name="restaurantFromCity"),

    # path('login/',views.login.as_view(),name="login"),

    # path('validate/', ValidateOTP.as_view(), name="validate"),
]

Eatler-Web-Application/main/urls.py
from django.conf.urls import url
from .views import homepage
from django.urls import path
# from .views import ProductFormView,RestaurantFormView
from .views import (RestaurantCreateView,RestaurantListView,RestaurantDetailView,RestaurantUpdateView,
                    RestaurantDeleteView,ProductCreateView,ProductUpdateView,ProductDeleteView,
                    MenuView,RestaurantMenuView,DeliveryMenuView,CheckoutView,CheckoutTakeawayView,handleRequest,integration,
                    updateStatus,chatbotCheckout,sendEmail,checkNumber,verifyOTP,ProfileView,DeleteAddress,BookTableView,
                    getFeedback)
app_name='main'

urlpatterns = [
    path('',homepage,name='homepage'),
    # path('add_product/',ProductFormView,name="add_product"),
    # path('add_restaurant/',RestaurantFormView,name="add_restaurant"),
    path('list/',RestaurantListView.as_view(),name="list_restaurant"),
    path('create/',RestaurantCreateView.as_view(),name="create_restaurant"),
    path('list/<int:pk>',RestaurantDetailView.as_view(),name="detail_restaurant"),
    path("update/<int:pk>/",RestaurantUpdateView.as_view(),name="update_restaurant"),
    path("delete/<int:pk>/",RestaurantDeleteView.as_view(),name="delete_restaurant"),

    path('<int:pk>/create_product/',ProductCreateView.as_view(),name="create_product"),
    path('update_product/<int:pk>',ProductUpdateView.as_view(),name="update_product"),
    path('delete_product/<int:pk>',ProductDeleteView.as_view(),name="delete_product"),

    path('menu/',MenuView,name="menu"),
    path('menu/<int:pk>/',RestaurantMenuView,name="restaurant_menu"),

    path('delivery_menu/',DeliveryMenuView,name="delivery_menu"),

    path('checkout/',CheckoutView,name="checkout_url"),

    path('checkout_takeaway/',CheckoutTakeawayView,name="checkout_takeaway_url"),

    path('handleRequest/',handleRequest,name='handleRequest'),



    path('integration/',integration,name='integration'),

    path('updateStatus/',updateStatus,name='updateStatus'),
    path('chatbotCheckout/',chatbotCheckout,name='chatbotCheckout'),
    # path('orderStatus/<int:order_id>',orderStatus,name='orderStatus'),
    path('sendemail/',sendEmail,name='sendemail'),
    path('sendfeedback/',getFeedback,name='sendfeedback'),


    path('check_number/',checkNumber,name='check_number'),
    path('verify_otp_number/',verifyOTP,name='verify_otp_number'),


    path('profile/',ProfileView,name="user_profile"),
    path('deleteAddress/',DeleteAddress,name="deleteAddress"),
    
    path('bookTable/',BookTableView,name="bookTable"),
    






]

Eatler-Web-Application/main/models.py
from django.db import models
from accounts.models import User
from django.shortcuts import redirect
from django.urls import reverse
import os
# Create your models here.
from django_google_maps import fields as map_fields
from datetime import date,datetime
from django.utils import timezone




class Restaurant(models.Model):

    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    short_description = models.CharField(max_length=200)
    long_description = models.TextField()
    photo = models.ImageField(upload_to='restaurant_images',blank=True)
    address = models.CharField(max_length=300)
    locality = models.CharField(max_length=200,default=None)
    city = models.CharField(max_length=200)
    email = models.EmailField()
    contact_number = models.IntegerField()
    latitude=models.FloatField(blank=True,null=True)
    longitude=models.FloatField(blank=True,null=True)
    open_time=models.TimeField(auto_now=False, auto_now_add=False)
    close_time=models.TimeField(auto_now=False, auto_now_add=False)
    rating = models.CharField(max_length=30,blank=True,default=None,null=True)
    northindian=models.BooleanField(default=True)
    southindian=models.BooleanField(default=True)
    chinese=models.BooleanField()
    continental=models.BooleanField()
    oriental=models.BooleanField()
    veg=models.BooleanField(default=True)
    non_veg=models.BooleanField(default=False)
    live_video=models.URLField(max_length=300,default="")

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("main:list")



TYPE = (
('VEG','veg'),
('NON_VEG','non_veg'),
)

CUISINE = (
('NorthIndian','northindian'),
('SouthIndian','southindian'),
('Chinese','chinese'),
('Continental','continental'),
('Oriental','oriental'),
)

CATEGORY = (
('Breakfast','breakfast'),
('Snacks','snacks'),
('Lunch/dinner','lunch/dinner'),
('Beverages','beverages'),
('Dessert/sweet','dessert/sweet')
)




class Product(models.Model):
    restaurant=models.ForeignKey(Restaurant,on_delete=models.CASCADE,related_name="products",default=None)
    name = models.CharField(max_length=300)
    short_description = models.CharField(max_length=200)
    long_description = models.TextField(blank=True)
    photo = models.ImageField(upload_to='product_images',blank=True)
    price = models.DecimalField(max_digits=6,decimal_places=2)
    add_on1 = models.CharField(max_length=200,default=None,blank=True)
    add_on2 = models.CharField(max_length=200,default=None,blank=True)
    add_on3 = models.CharField(max_length=200,default=None,blank=True)
    add_on4 = models.CharField(max_length=200,default=None,blank=True)
    add_on5 = models.CharField(max_length=200,default=None,blank=True)
    type = models.CharField(max_length=20,choices=TYPE,default='Veg')
    cuisine = models.CharField(max_length=20,choices=CUISINE,default='NothIndian')
    category = models.CharField(max_length=30,choices=CATEGORY,default='Lunch/Dinner')
    rating = models.CharField(max_length=30,blank=True,default=None,null=True)

    def __str__(self):
        return self.name



class Order(models.Model):
    order_id=models.AutoField(primary_key=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    restaurant=models.ForeignKey(Restaurant,on_delete=models.CASCADE)
    phone_number=models.CharField(max_length=111)
    item_jsons=models.CharField(max_length=6000)
    name = models.CharField(max_length=300)
    email = models.EmailField(max_length=200)
    shipping_address = models.CharField(max_length=200,default="")
    billing_address = models.CharField(max_length=200,default="")
    state = models.CharField(max_length=200,default="")
    country = models.CharField(max_length=200,default="")
    order_time=models.TimeField(auto_now_add=True,editable=True)
    order_date=models.DateField(auto_now_add=True,editable=True)
    zip_code = models.CharField(max_length=200,blank=True,null=True,default="")
    total_price=models.CharField(max_length=50,blank=True,null=True)
    order_status=models.CharField(max_length=200,default="not_placed")
    payment_status=models.BooleanField(default=False)
    payment_mode=models.CharField(max_length=200,default="")
    special_instruction=models.CharField(max_length=1000,default="")
    how=models.CharField(max_length=30,default="delivery")
    schedule_date=models.DateField(auto_now_add=False,editable=True,default=None,blank=True)
    schedule_time=models.TimeField(auto_now_add=False,editable=True,default=None,blank=True)
    session_id=models.CharField(max_length=300,default=None,null=True)





class Address(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    address = models.CharField(max_length=200,unique=True)

    def __str__(self):
        return self.address

STATUS=(
    ('Resolved','resolved'),
    ('Unresolved','unresolved')
)

class Issues(models.Model):

    first_name=models.CharField(max_length=20)
    last_name=models.CharField(max_length=20)
    phone_number=models.IntegerField()
    subject=models.CharField(max_length=150)
    message=models.CharField(max_length=1000)
    category=models.CharField(max_length=20)
    file = models.FileField(upload_to='Issues',blank=True)
    status=models.CharField(choices=STATUS,max_length=30,default='Unresolved')
    email=models.EmailField()

    def _str_(self):
        return self.first_name





class UserInfo(models.Model):
    user_info_id=models.AutoField(primary_key=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    email = models.EmailField(default="",blank=True)
    photo = models.ImageField(upload_to='user_image',blank=True)


    def __str__(self):
        return self.user.full_name




class BookTable(models.Model):
    book_id=models.AutoField(primary_key=True)
    restaurant=models.ForeignKey(Restaurant,on_delete=models.CASCADE)
    user_name=models.CharField(max_length=30)
    user_email=models.EmailField()
    user_phone_number=models.IntegerField()
    date=models.DateField(auto_now_add=False,editable=True,default=None,blank=True)
    time=models.TimeField(auto_now_add=False,editable=True,default=None,blank=True)
    number_of_people=models.IntegerField(default=0)
    message=models.CharField(max_length=400,blank=True)



class Feedback(models.Model):
    feedback_id=models.AutoField(primary_key=True)
    message=models.CharField(max_length=2000)
    feedback_type=models.CharField(max_length=30)
    feedback_category=models.CharField(max_length=30)

#cancel reason 
#delivery person
#delivery charge
#deliverable time how much time required to reach the destination




# pending
# confirm
# preparing
# outfordelivery
# cancelled
# delivered






#delivery
#checkout me address ko validate karna and calculate delivery charge accordingly
#cancel ka reason puchna
#modify order model

Eatler-Web-Application/main/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext as _
from django.contrib.auth import authenticate
from .models import Product,Restaurant


TYPE = (
('VEG','veg'),
('NON_VEG','non_veg'),
)

CUISINE = (
('NorthIndian','northindian'),
('SouthIndian','southindian'),
('Chinese','chinese'),
('Continental','continental'),
('Oriental','oriental'),
)

CATEGORY = (
('Breakfast','breakfast'),
('Snacks','snacks'),
('Lunch/dinner','lunch/dinner'),
('Beverages','beverages'),
('Dessert/sweet','dessert/sweet')
)


class ProductForm(forms.ModelForm):



    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control',}))
    short_description = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control',}))
    long_description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control',}))
    photo = forms.ImageField(required=False,widget=forms.FileInput(attrs={'class':'form-control-file',}))
    price = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control',}))
    add_on1 = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control',}))
    add_on2 = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control',}))
    add_on3 = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control',}))
    add_on4 = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control',}))
    add_on5 = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control',}))
    type = forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control',}),choices=TYPE)
    cuisine = forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control',}),choices=CUISINE)
    category = forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control',}),choices=CATEGORY)

    class Meta:
        model = Product
        exclude = ('restaurant','rating')



class RestaurantForm(forms.ModelForm):
   
   
    
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control',},))
    short_description = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control' }))
    long_description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    locality = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    city = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    photo = forms.ImageField(widget=forms.FileInput(attrs={'class':'form-control-file'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    contact_number = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control'}))
    open_time=forms.TimeField(widget=forms.TimeInput(attrs={'class':'form-control'}))
    close_time=forms.TimeField(widget=forms.TimeInput(attrs={'class':'form-control'}))
    northindian=forms.BooleanField(initial=True,required=False,widget=forms.CheckboxInput(attrs={'class':'form-check-input'}))
    southindian=forms.BooleanField(initial=True,required=False,widget=forms.CheckboxInput(attrs={'class':'form-check-input'}))
    chinese=forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={'class':'form-check-input'}))
    continental=forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={'class':'form-check-input'}))
    oriental=forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={'class':'form-check-input'}))
    veg=forms.BooleanField(initial=True,required=False,widget=forms.CheckboxInput(attrs={'class':'form-check-input'}))
    non_veg=forms.BooleanField(initial=False,required=False,widget=forms.CheckboxInput(attrs={'class':'form-check-input'}))
    live_video=forms.URLField(widget=forms.URLInput(attrs={'class':'form-control'}))

    class Meta:
        model = Restaurant
        exclude = ('user','rating','latitude','longitude')











class RestaurantFormUpdate(forms.ModelForm):
   
    
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control',},))
    short_description = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control' }))
    long_description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))
    photo = forms.ImageField(required=False,widget=forms.FileInput(attrs={'class':'form-control-file',}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    contact_number = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control'}))
    open_time=forms.TimeField(widget=forms.TimeInput(attrs={'class':'form-control'}))
    close_time=forms.TimeField(widget=forms.TimeInput(attrs={'class':'form-control'}))
    northindian=forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={'class':'form-check-input'}))
    southindian=forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={'class':'form-check-input'}))
    chinese=forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={'class':'form-check-input'}))
    continental=forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={'class':'form-check-input'}))
    oriental=forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={'class':'form-check-input'}))
    live_video=forms.URLField(widget=forms.URLInput(attrs={'class':'form-control'}))


    class Meta:
        model = Restaurant
        exclude = ('user','rating','latitude','longitude','address','locality','city')


  

Eatler-Web-Application/main/templates/main/restaurant_confirm_delete.html
{% extends "main/base.html" %}
{% load static %}

{% block body %}
<style>
    .container{
    align-items:center;
    justify-content:center;
    display:flex;
    }
    body{
      background:#e9ecef;
        margin:0 auto;
    }
    .fff{
      background:white;
      width:40%;
      height:40%;
      margin-top:50px;
    }
}
</style>
<div class="container" style="height:100%; width:100%; margin:auto;">

  <div class="fff" style="text-align:center;">
    <h5 class="card-title my-2 mx-2">Delete {{restaurant.name}}?</h5>
  <div class="card-body">
    <form method="post">
      {%csrf_token%}
      <input type="submit" class="btn btn-danger" value="Delete">
      <a   class="btn btn-warning" href="{%url 'main:list_restaurant'%}">Cancel</a>
    </form>
  </div>
</div>


</div>
{% endblock%}

Eatler-Web-Application/main/templates/main/restaurant_form.html
{% extends "main/base.html" %}
{% load static %}





{% block body %}






  
<div class="container">
 
    {%if not form.instance.pk%}
     <h2 class="my-4">Add Restaurant</h2>
    
    <form  method="post" enctype="multipart/form-data">
    
    {%csrf_token%}
    {{form.errors}}


    <div class="form-group row">
        <label for="id_name" class="col-sm-2 col-form-label">Name </label>
        <div class="col-sm-10">
        {{form.name}}
        </div>
    </div>

    <div class="form-group row">
        <label for="id_contact_number" class="col-sm-2 col-form-label">Contact Number </label>
        <div class="col-sm-10">
        {{form.contact_number}}
        </div>
    </div>


    <div class="form-group row">
        <label for="id_email" class="col-sm-2 col-form-label">Email </label>
        <div class="col-sm-10">
        {{form.email}}
        </div>
    </div>


    <div class="form-group row">
        <label for="id_short_description" class="col-sm-2 col-form-label">Short Description </label>
        <div class="col-sm-10">
        {{form.short_description}}
        </div>
    </div>


    <div class="form-group row">
        <label for="id_long_description" class="col-sm-2 col-form-label">Long Description </label>
        <div class="col-sm-10">
        {{form.long_description}}
        </div>
    </div>

 <div class="form-group row">
        <label for="id_photo" class="col-sm-2 col-form-label">Photo </label>
        <div class="col-sm-10">
        {{form.photo}}
        </div>
    </div>




    <div class="form-group row">
        <label for="id_address" class="col-sm-2 col-form-label">Address </label>
        <div class="col-sm-10">
        {{form.address}}
        </div>
    </div>



   

    <div class="form-group row">
        <label for="id_locality" class="col-sm-2 col-form-label">Locality </label>
        <div class="col-sm-10">
        {{form.locality}}
        </div>
    </div>

    <div class="form-group row">
        <label for="id_city" class="col-sm-2 col-form-label">City </label>
        <div class="col-sm-10">
        {{form.city}}
        </div>
    </div>



    <div class="form-group row">
        <label for="id_live_video" class="col-sm-2 col-form-label">Live Video URL </label>
        <div class="col-sm-10">
        {{form.live_video}}
        </div>
    </div>

  <div class="form-group row">
        <label for="id_open_time" class="col-sm-2 col-form-label">Open Time </label>
        <div class="col-sm-10">
        {{form.open_time}}
        </div>
    </div>


    <div class="form-group row">
        <label for="id_close_time" class="col-sm-2 col-form-label">Close Time </label>
        <div class="col-sm-10">
        {{form.close_time}}
        </div>
    </div>


    

    <div class="form-group row">
      <label for="belowdiv" class="col-sm-2 col-form-label">Select Cuisines</label>
      <div id="belowdiv"class="row col-sm-10 my-2">
            <div class="form-group form-check mx-2">
                {{form.northindian}}
                <label for="id_northindian" class="form-check-label">NorthIndian</label>
            </div>

              <div class="form-group form-check mx-2">
                {{form.southindian}}
                <label for="id_southindian" class="form-check-label">SouthIndian</label>
              </div>
            <div class="form-group form-check mx-2">
                {{form.chinese}}
                <label for="id_southindian" class="form-check-label">Chinese</label>
            </div>
            <div class="form-group form-check mx-2">
                {{form.continental}}
                <label for="id_southindian" class="form-check-label">Continental</label>
            </div>
            <div class="form-group form-check mx-2">
                {{form.oriental}}
                <label for="id_southindian" class="form-check-label">Oriental</label>
            </div>
      </div>
  </div>


    <div class="form-group row">
            <label for="belowdiv2" class="col-sm-2 col-form-label">Select Type</label>
            <div id="belowdiv"class="row col-sm-10 my-2">
                  <div class="form-group form-check mx-2">
                      {{form.veg}}
                      <label for="id_veg" class="form-check-label">VEG</label>
                  </div>

                    <div class="form-group form-check mx-2">
                      {{form.non_veg}}
                      <label for="id_non_veg" class="form-check-label">NON-VEG</label>
                  </div>
               
            </div>
      </div>






     
    <input type="submit" class="btn btn-primary"  value="submit">
  </form>

</div>
    
    {%else%}
    <div class="container">
            <h2 class="my-4">Update Restaurant</h2>
            <form  method="post" enctype="multipart/form-data">
            
            {%csrf_token%}
            {{form.errors}}


            <div class="form-group row">
                <label for="id_name" class="col-sm-2 col-form-label">Name </label>
                <div class="col-sm-10">
                {{form.name}}
                </div>
            </div>

            <div class="form-group row">
                <label for="id_contact_number" class="col-sm-2 col-form-label">Contact Number </label>
                <div class="col-sm-10">
                {{form.contact_number}}
                </div>
            </div>


            <div class="form-group row">
                <label for="id_email" class="col-sm-2 col-form-label">Email </label>
                <div class="col-sm-10">
                {{form.email}}
                </div>
            </div>


            <div class="form-group row">
                <label for="id_short_description" class="col-sm-2 col-form-label">Short Description </label>
                <div class="col-sm-10">
                {{form.short_description}}
                </div>
            </div>


            <div class="form-group row">
                <label for="id_long_description" class="col-sm-2 col-form-label">Long Description </label>
                <div class="col-sm-10">
                {{form.long_description}}
                </div>
            </div>

         <div class="form-group row">
                <label for="id_photo" class="col-sm-2 col-form-label">Photo </label>
                <div class="col-sm-10">
                {{form.photo}}
                </div>
            </div>

            <div class="form-group row">
              <label for="id_live_video" class="col-sm-2 col-form-label">Live Video URL </label>
              <div class="col-sm-10">
              {{form.live_video}}
              </div>
           </div>

          <div class="form-group row">
                <label for="id_open_time" class="col-sm-2 col-form-label">Open Time </label>
                <div class="col-sm-10">
                {{form.open_time}}
                </div>
            </div>


            <div class="form-group row">
                <label for="id_close_time" class="col-sm-2 col-form-label">Close Time </label>
                <div class="col-sm-10">
                {{form.close_time}}
                </div>
            </div>

            <div class="form-group row">
                <label for="belowdiv" class="col-sm-2 col-form-label">Select Cuisines</label>
                <div id="belowdiv"class="row col-sm-10 my-2">
                      <div class="form-group form-check mx-2">
                          {{form.northindian}}
                          <label for="id_northindian" class="form-check-label">NorthIndian</label>
                      </div>

                        <div class="form-group form-check mx-2">
                          {{form.southindian}}
                          <label for="id_southindian" class="form-check-label">SouthIndian</label>
                      </div>
                      <div class="form-group form-check mx-2">
                          {{form.chinese}}
                          <label for="id_southindian" class="form-check-label">Chinese</label>
                      </div>
                      <div class="form-group form-check mx-2">
                          {{form.continental}}
                          <label for="id_southindian" class="form-check-label">Continental</label>
                      </div>
                      <div class="form-group form-check mx-2">
                          {{form.oriental}}
                          <label for="id_southindian" class="form-check-label">Oriental</label>
                      </div>
                </div>
          </div>


          <div class="form-group row">
                <label for="belowdiv2" class="col-sm-2 col-form-label">Select Type</label>
                <div id="belowdiv"class="row col-sm-10 my-2">
                      <div class="form-group form-check mx-2">
                          {{form.veg}}
                          <label for="id_veg" class="form-check-label">VEG</label>
                      </div>

                        <div class="form-group form-check mx-2">
                          {{form.non_veg}}
                          <label for="id_non_veg" class="form-check-label">NON-VEG</label>
                      </div>
                   
                </div>
          </div>
             
            <input type="submit" class="btn btn-primary"  value="submit">
          </form>

        </div>

    {%endif%}
  
  

{% endblock %}

Eatler-Web-Application/main/templates/main/takeaway.html
{% extends "main/mainbase.html"%}
{% block content %}
  <style>
  .card{
  margin: 10px auto;
  float: none;
  margin-bottom: 10px;
  }
  </style>
  <br><br><br><br><br>
  <div class="container">
    <div class="restaurant-list">
      {% for item in restaurant%}
        <div class="card mb-3" style="max-width: 80%;">
          <div class="row no-gutters">
            <div class="col-md-4">
              <img src="/media/{{item.photo}}" class="card-img" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{item.name}}</h5>
                <p class="card-text">{{item.description}}</p>
                <p class="card-text">Address : {{item.address}}</p>
                <p class="card-text">City : {{item.city}}</p>
                <p class="card-text">Contact Number : {{item.contact_number}}</p>
                <p class="card-text"><small class="text-muted">  <a class="btn btn-success" href="{% url 'main:restaurant_menu' pk=item.pk %}">View Menu</a> </small></p>
              </div>
            </div>
          </div>
        </div>
        <br>
      {% endfor %}
    </div>
  </div>
  <br>
  {% block js %}
    <script type="text/javascript">
    $(document).ready(function(){
    if(localStorage.getItem('method')==null){
    var method = '{{ method}}'
    localStorage.setItem('method',method);
    }
    
    });
    </script>
  {% endblock %}
{% endblock content %}